# Generated by Django 5.1 on 2024-12-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_ventas', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_empleado', models.PositiveIntegerField()),
                ('id_cliente', models.PositiveIntegerField()),
                ('id_producto', models.PositiveIntegerField()),
                ('fecha_venta', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('id_sucursal', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
            ],
        ),
    ]
